-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."writtenspells" add column "castable" boolean
--  null default 'false';
